### ISSUE TITLE
Stable Diffusion 1.5 推理报错

### ISSUE THREAD

**Issue by VSRacer** [mindspore-lab/mindone#207]
### 测试平台：Modelarts-Notebook
镜像环境：mindspore_2.1.0-cann_6.3.2-py_3.7-euler_2.8.3-aarch64-d910
执行命令：python text_to_image.py --prompt "雪中之狼"  -v 1.5-wukong
报错日志：
```
(MindSpore) [ma-user stable_diffusion_v2]$python text_to_image.py --prompt "雪中之狼"  -v 1.5-wukong
flash attention is available.
[2023-11-01 14:05:03] INFO: Loading model from models/wukong-huahua-ms.ckpt
[WARNING] ME(28702:281473370352496,MainProcess):2023-11-01-14:05:52.538.406 [mindspore/train/serialization.py:170] The type of cond_stage_model.transformer.embedding_table:Float32 in 'parameter_dict' is different from the type of it in 'net':Float16, then the type convert from Float32 to Float16 in the network.
[WARNING] ME(28702:281473370352496,MainProcess):2023-11-01-14:05:52.808.218 [mindspore/train/serialization.py:170] The type of cond_stage_model.transformer.positional_embedding:Float32 in 'parameter_dict' is different from the type of it in 'net':Float16, then the type convert from Float32 to Float16 in the network.
[2023-11-01 14:05:53] INFO: Prediction type: noise
[2023-11-01 14:06:42] INFO: Key Settings:
==================================================
MindSpore mode[GRAPH(0)/PYNATIVE(1)]: 0
Distributed mode: False
Number of input prompts: 1
Number of input negative prompts: 1
Number of trials for each prompt: 2
Number of samples in each trial: 4
Model: StableDiffusion v-1.5-wukong
Precision: Float16
Pretrained ckpt path: models/wukong-huahua-ms.ckpt
Lora ckpt path: None
Sampler: dpm_solver_pp
Sampling steps: 20
Uncondition guidance scale: 7.5
Target image size (H, W): (512, 512)
==================================================
[2023-11-01 14:06:42] INFO: [1/1] Generating images with conditions:
Prompt(s): 雪中之狼
Negative prompt(s): 


[WARNING] DEVICE(28702,fffe6742d1e0,python):2023-11-01-14:25:31.949.298 [mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:801] GetDumpPath] The environment variable 'MS_OM_PATH' is not set, the files will save to the process local path, as ./rank_id/node_dump/...
[ERROR] DEVICE(28702,fffe6742d1e0,python):2023-11-01-14:25:31.950.434 [mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:819] PrintDebugInfoAndDumpFailNode] Task fail infos, rt task_id: 21, rt stream_id: 5, tid: 28702, device_id: 0, retcode: 507011 ( model execute failed)
[ERROR] DEVICE(28702,fffe6742d1e0,python):2023-11-01-14:25:31.951.099 [mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:828] PrintDebugInfoAndDumpFailNode] Task DebugString, Tbetask: task name: Default/transformer_layer-Transformer/resblocks-SequentialCell/0-ResidualAttentionBlock/attn-AttentionWithMask/attn-MultiheadAttention/FusionOp_BatchMatMul_Add-op1536_124298, stub_func: te_fusion_batch_matmul_add_14963448916587766608_0__kernel0, mindspore stream_id: 0, stream_: 0xaaac1695cf00, block_dim: 24, dump_flag: 0, args_size: 40, input_data_addr: [0]: 0x1241802b5400, [1]: 0x124180116000, [2]: 0x1248f8fc0600, output_data_addr: [0]: 0x124180000000, workspace_addr: [0]: 0x12418008b000
[WARNING] DEVICE(28702,fffe6742d1e0,python):2023-11-01-14:25:31.965.780 [mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:837] PrintDebugInfoAndDumpFailNode] Dump task error infos (input/output's value) for node:[Default/transformer_layer-Transformer/resblocks-SequentialCell/0-ResidualAttentionBlock/attn-AttentionWithMask/attn-MultiheadAttention/FusionOp_BatchMatMul_Add-op1536], save path: ./rank_0/node_dump, 
The function call stack:
Corresponding code candidate:
 - In file /home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/ops/function/math_func.py:327/    return _get_cache_prim(P.Add)()(input, other)/
   In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/encoders/text_encoder.py:53/        attn_output_weights += self.expand_dims(attn_mask, 0)/
   In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/encoders/text_encoder.py:69/        return self.attn(x, x, x, self.attn_mask)/
   In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/encoders/text_encoder.py:92/        x = x + self.attn(self.ln_1(x))/
   In file /home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/layer/container.py:281/            input_data = cell(input_data)/
   In file /home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/layer/container.py:280/        for cell in self.cell_list:/
   In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/encoders/text_encoder.py:119/        return self.resblocks(x)/
   In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/encoders/text_encoder.py:172/        x = self.transformer_layer(x)/
 - In file /home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/ops/function/math_func.py:9486/        res = _batch_matmul(input, other)/
   In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/encoders/text_encoder.py:52/        attn_output_weights = ops.matmul(q, k.transpose((0, 2, 1)))  # bs x (HW + 1) x (HW + 1)/
   In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/encoders/text_encoder.py:69/        return self.attn(x, x, x, self.attn_mask)/
   In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/encoders/text_encoder.py:92/        x = x + self.attn(self.ln_1(x))/
   In file /home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/layer/container.py:281/            input_data = cell(input_data)/
   In file /home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/layer/container.py:280/        for cell in self.cell_list:/
   In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/encoders/text_encoder.py:119/        return self.resblocks(x)/
   In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/encoders/text_encoder.py:172/        x = self.transformer_layer(x)/

[WARNING] DEVICE(28702,fffe6742d1e0,python):2023-11-01-14:25:31.969.610 [mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:801] GetDumpPath] The environment variable 'MS_OM_PATH' is not set, the files will save to the process local path, as ./rank_id/exec_order/...
[ERROR] DEVICE(28702,fffe6742d1e0,python):2023-11-01-14:25:31.979.197 [mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:906] DumpDebugInfoFile] Execute order has saved at /home/ma-user/work/mindone/examples/stable_diffusion_v2/rank_0/exec_order/kernel_graph_7.csv
Traceback (most recent call last):
  File "text_to_image.py", line 497, in <module>
    main(args)
  File "text_to_image.py", line 255, in main
    uc = model.get_learned_conditioning(tokenized_negative_prompts)
  File "/home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/ddpm.py", line 335, in get_learned_conditioning
    c = self.cond_stage_model.encode(c)
  File "/home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/encoders/modules.py", line 72, in encode
    outputs = self.transformer(tokenized_text)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/cell.py", line 639, in __call__
    out = self.compile_and_run(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/cell.py", line 966, in compile_and_run
    return _cell_graph_executor(self, *new_args, phase=self.phase)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/common/api.py", line 1674, in __call__
    return self.run(obj, *args, phase=phase)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/common/api.py", line 1713, in run
    return self._exec_pip(obj, *args, phase=phase_real)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/common/api.py", line 106, in wrapper
    results = fn(*arg, **kwargs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/common/api.py", line 1693, in _exec_pip
    return self._graph_executor(args, phase)
RuntimeError: Run task for graph:kernel_graph_7 error! The details refer to 'Ascend Error Message'.

----------------------------------------------------
- Ascend Error Message:
----------------------------------------------------
EZ9999: Inner Error!
EZ9999  The error from device(chipId:1, dieId:0), serial number is 1, there is an fftsplus aicore error exception, core id is 24, error code = 0, dump info: pc start: 0x1240c0060000, current: 0x1240c0060338, vec error info: 0, mte error info: 0x298b7f98e9, ifu error info: 0x252f38f386bc0, ccu error info: 0x4c156e3a2f0a9008, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd000288, para base: 0x1240c005f000.[FUNC:ProcessStarsCoreErrorInfo][FILE:device_error_proc.cc][LINE:1091]
        TraceBack (most recent call last):
        The extend info: errcode:(0, 0, 0) errorStr: timeout or trap error. fixp_error0 info: 0xb7f98e9, fixp_error1 info: 0x29 fsmId:0, tslot:0, thread:0, ctxid:0, blk:0, sublk:0, subErrType:4.[FUNC:ProcessStarsCoreErrorInfo][FILE:device_error_proc.cc][LINE:1103]
        The error from device(chipId:1, dieId:0), serial number is 2, there is an fftsplus aivector error exception, core id is 15, error code = 0, dump info: pc start: 0x1240c00603bc, current: 0x1240c006047c, vec error info: 0xdb1bfec002, mte error info: 0x8c380503b2, ifu error info: 0x240dc7e16f9c0, ccu error info: 0x8c5713005da23009, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd000288, para base: 0x1240c005f000.[FUNC:ProcessStarsCoreErrorInfo][FILE:device_error_proc.cc][LINE:1091]
        The extend info: errcode:(0, 0, 0) errorStr: timeout or trap error. fixp_error0 info: 0x80503b2, fixp_error1 info: 0x8c fsmId:0, tslot:0, thread:0, ctxid:0, blk:0, sublk:0, subErrType:4.[FUNC:ProcessStarsCoreErrorInfo][FILE:device_error_proc.cc][LINE:1103]
        Aicore kernel execute failed, device_id=0, stream_id=5, report_stream_id=2, task_id=21, flip_num=0, fault kernel_name=te_fusion_batch_matmul_add_14963448916587766608_0__kernel0, program id=22, hash=15304113375623613237.[FUNC:GetError][FILE:stream.cc][LINE:1418]
        [AIC_INFO] after execute:args print end[FUNC:GetError][FILE:stream.cc][LINE:1418]
        rtStreamSynchronize execute failed, reason=[the model stream execute failed][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:50]

(Please search "Ascend Error Message" at https://www.mindspore.cn for error code description)

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/plugin/device/ascend/hal/hardware/ascend_graph_executor.cc:296 RunGraph
```

**Comment by xiejx** [comment]
请问您是怎么解决这个报错的？
