### ISSUE TITLE
ImportError: cannot import name 'FlashAttention' from 'gm.modules.attention' (/home/ma-user/work/mindone/examples/pangu_draw_v3/gm/modules/attention.py)

### ISSUE THREAD

**Issue by 913363043** [mindspore-lab/mindone#268]
Thanks for sending an issue!  Here are some tips for you:

If this is your first time, please read our contributor guidelines: https://github.com/mindspore-ai/mindspore/blob/master/CONTRIBUTING.md

## Hardware Environment | 硬件环境
 -  please tell us what kind of hardware can reproduce your error?
  请告诉我们您报错的后端类型
    - [] `Ascend`

### Software Environment | 软件环境
- MindSpore version:
请告诉我们您正在使用的MindSpore版本：
  - 2.0.0
- Python version(e.g., 3.7.10):
- EulerOS 2.0 (SP8), CANN-6.0.RC1
- GCC/Compiler version:

## Describe the current behavior | 目前输出
目前的输出是pangu_draw_v3/run_sampling.sh 、 目前的报错是关于flash attention is unavailable.
## Steps to reproduce the issue | 复现报错的步骤
bash pangu_draw_v3/run_sampling

## Related log / screenshot | 完整日志
(MindSpore) [ma-user pangu_draw_v3]$bash run_sampling.shflash attention is unavailable.
constructing SpatialTransformer of depth 2 w/ 640 channels and 10 heads
constructing SpatialTransformer of depth 2 w/ 640 channels and 10 heads
constructing SpatialTransformer of depth 10 w/ 1280 channels and 20 heads
constructing SpatialTransformer of depth 10 w/ 1280 channels and 20 heads
constructing SpatialTransformer of depth 10 w/ 1280 channels and 20 heads
constructing SpatialTransformer of depth 10 w/ 1280 channels and 20 heads
constructing SpatialTransformer of depth 10 w/ 1280 channels and 20 heads
constructing SpatialTransformer of depth 10 w/ 1280 channels and 20 heads
constructing SpatialTransformer of depth 2 w/ 640 channels and 10 heads
constructing SpatialTransformer of depth 2 w/ 640 channels and 10 heads
constructing SpatialTransformer of depth 2 w/ 640 channels and 10 heads
Initialized embedder #0: FrozenCnCLIPEmbedder with 115972685 params. Trainable: False
Initialized embedder #1: FrozenOpenCLIPEmbedder2 with 694665770 params. Trainable: False
Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
Traceback (most recent call last):
  File "/home/ma-user/work/mindone/examples/pangu_draw_v3/pangu_sampling.py", line 454, in <module>
    sample(args)
  File "/home/ma-user/work/mindone/examples/pangu_draw_v3/pangu_sampling.py", line 322, in sample
    model, filter = create_model(
  File "/home/ma-user/work/mindone/examples/pangu_draw_v3/gm/helpers.py", line 160, in create_model
    model = load_model_from_config(config.model, checkpoints, amp_level=amp_level)
  File "/home/ma-user/work/mindone/examples/pangu_draw_v3/gm/helpers.py", line 272, in load_model_from_config
    model = instantiate_from_config(model_config)
  File "/home/ma-user/work/mindone/examples/pangu_draw_v3/gm/util/util.py", line 46, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/ma-user/work/mindone/examples/pangu_draw_v3/gm/models/diffusion.py", line 52, in __init__
    self.first_stage_model = self.init_freeze_first_stage(first_stage_config)
  File "/home/ma-user/work/mindone/examples/pangu_draw_v3/gm/models/diffusion.py", line 76, in init_freeze_first_stage
    model = instantiate_from_config(config)
  File "/home/ma-user/work/mindone/examples/pangu_draw_v3/gm/util/util.py", line 46, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/ma-user/work/mindone/examples/pangu_draw_v3/gm/util/util.py", line 56, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ma-user/work/mindone/examples/pangu_draw_v3/gm/models/autoencoder.py", line 4, in <module>
    from gm.modules.diffusionmodules.model import Decoder, Encoder
  File "/home/ma-user/work/mindone/examples/pangu_draw_v3/gm/modules/diffusionmodules/model.py", line 5, in <module>
    from gm.modules.attention import FLASH_IS_AVAILABLE, FlashAttention, LinearAttention
ImportError: cannot import name 'FlashAttention' from 'gm.modules.attention' (/home/ma-user/work/mindone/examples/pangu_draw_v3/gm/modules/attention.py)
## Special notes for this issue | 其他信息
没有更改配置文件,环境配置好了

**Comment by zhanghuiyao** [comment]
@townwish4git

**Comment by 913363043** [comment]
ms2.0.0版本问题，这个删掉了flashattention
