### ISSUE TITLE
使用sd_v2_768_v-e12e3a9b.ckpt模型生成768*768图片的时候报错

### ISSUE THREAD

**Issue by jxzhang789** [mindspore-lab/mindone#503]
Thanks for sending an issue!  Here are some tips for you:

If this is your first time, please read our contributor guidelines: https://github.com/mindspore-ai/mindspore/blob/master/CONTRIBUTING.md

## Hardware Environment | 硬件环境
 -  please tell us what kind of hardware can reproduce your error?
  请告诉我们您报错的后端类型
Ascend 910

### Software Environment | 软件环境
- MindSpore version: mindspore2.0.0rc1_cann_6.3.rc1.alpha001
- Python version: 3.7.10
- OS(e.g., Linux Ubuntu 16.04)
- GCC/Compiler version:

## Describe the current behavior | 目前输出
[WARNING] KERNEL(194308,ffffaece6a40,python):2024-05-17-18:13:56.260.136 [mindspore/ccsrc/plugin/device/ascend/kernel/tbe/tbe_kernel_compile.cc:638] UpdateFusionTypeAndOutputDataDesc] mul_15449895951707069681_0 not in prebuild_res_map_. Op name: Default/diffusion_model-UNetModel/input_blocks-CellList/1-CellList/1-SpatialTransformer/transformer_blocks-CellList/0-BasicTransformerBlock/attn1-CrossAttention/attention-Attention/Mul-op3720
[WARNING] KERNEL(194308,ffffaece6a40,python):2024-05-17-18:13:56.270.449 [mindspore/ccsrc/plugin/device/ascend/kernel/tbe/tbe_kernel_compile.cc:638] UpdateFusionTypeAndOutputDataDesc] mul_15449895951707069681_0 not in prebuild_res_map_. Op name: Default/diffusion_model-UNetModel/input_blocks-CellList/2-CellList/1-SpatialTransformer/transformer_blocks-CellList/0-BasicTransformerBlock/attn1-CrossAttention/attention-Attention/Mul-op3933
[WARNING] KERNEL(194308,ffffaece6a40,python):2024-05-17-18:13:56.420.789 [mindspore/ccsrc/plugin/device/ascend/kernel/tbe/tbe_kernel_compile.cc:638] UpdateFusionTypeAndOutputDataDesc] mul_15449895951707069681_0 not in prebuild_res_map_. Op name: Default/diffusion_model-UNetModel/output_blocks-CellList/9-CellList/1-SpatialTransformer/transformer_blocks-CellList/0-BasicTransformerBlock/attn1-CrossAttention/attention-Attention/Mul-op6950
[WARNING] KERNEL(194308,ffffaece6a40,python):2024-05-17-18:13:56.430.991 [mindspore/ccsrc/plugin/device/ascend/kernel/tbe/tbe_kernel_compile.cc:638] UpdateFusionTypeAndOutputDataDesc] mul_15449895951707069681_0 not in prebuild_res_map_. Op name: Default/diffusion_model-UNetModel/output_blocks-CellList/10-CellList/1-SpatialTransformer/transformer_blocks-CellList/0-BasicTransformerBlock/attn1-CrossAttention/attention-Attention/Mul-op7167
[WARNING] KERNEL(194308,ffffaece6a40,python):2024-05-17-18:13:56.440.425 [mindspore/ccsrc/plugin/device/ascend/kernel/tbe/tbe_kernel_compile.cc:638] UpdateFusionTypeAndOutputDataDesc] mul_15449895951707069681_0 not in prebuild_res_map_. Op name: Default/diffusion_model-UNetModel/output_blocks-CellList/11-CellList/1-SpatialTransformer/transformer_blocks-CellList/0-BasicTransformerBlock/attn1-CrossAttention/attention-Attention/Mul-op7383
Traceback (most recent call last):
  File "text_to_image.py", line 592, in <module>
    main(args)
  File "text_to_image.py", line 315, in main
    x_T=start_code,
  File "/home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/dpm_solver/sampler.py", line 112, in sample
    return_intermediate=True,
  File "/home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/dpm_solver/dpm_solver.py", line 1387, in sample
    model_prev_list = [self.model_fn(x, t)]
  File "/home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/dpm_solver/dpm_solver.py", line 499, in model_fn
    return self.data_prediction_fn(x, t)
  File "/home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/dpm_solver/dpm_solver.py", line 487, in data_prediction_fn
    noise = self.noise_prediction_fn(x, t)
  File "/home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/dpm_solver/dpm_solver.py", line 481, in noise_prediction_fn
    return self.model(x, t)
  File "/home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/dpm_solver/dpm_solver.py", line 369, in model_fn
    noise_output = noise_pred_fn(x_in, t_in, cond=c_in)
  File "/home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/dpm_solver/dpm_solver.py", line 313, in noise_pred_fn
    output = model(x, t_input, cond, **model_kwargs)
  File "/home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/dpm_solver/sampler.py", line 90, in <lambda>
    lambda x, t, c: self.model.apply_model(x, t, c),
  File "/home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/ddpm.py", line 382, in apply_model
    x_recon = self.model(x_noisy, t, **cond, **kwargs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/cell.py", line 636, in __call__
    out = self.compile_and_run(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/cell.py", line 957, in compile_and_run
    self.compile(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/cell.py", line 935, in compile
    jit_config_dict=self._jit_config_dict, *args, **kwargs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/common/api.py", line 1384, in compile
    result = self._graph_executor.compile(obj, args, kwargs, phase, self._use_vm_mode())
RuntimeError: TBE Single op compile failed. Compile failed op number:5, failed log:op: mul_15449895951707069681_0.

----------------------------------------------------
- Operator Compilation Exception Message: (For framework developers)
----------------------------------------------------
2024-05-17 10:14:04.017633+00:00: Query except_msg:Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/te_fusion/parallel_compilation.py", line 1651, in run
    optional_input_mode=self._optional_input_mode)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/te_fusion/fusion_manager.py", line 1543, in build_single_op
    json_file_path = call_op()
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/te_fusion/fusion_manager.py", line 1526, in call_op
    json_file_path = build_static_op(op_info, new_attrs, caxis_valus)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/te_fusion/fusion_manager.py", line 1454, in build_static_op
    opfunc(*inputs, *outputs, *new_attrs, **kwargs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/tbe/common/register/operation_func_mgr.py", line 197, in wrapper
    return func(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/tbe/common/utils/para_check.py", line 547, in _in_wrapper
    return func(*args, **kwargs)
  File "/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/impl/dynamic/mul.py", line 1185, in mul
    res = mul_compute(data_x1, data_x2, output, kernel_name)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/tbe/common/register/operation_func_mgr.py", line 157, in wrapper
    tmp_res = func(*new_args, **kwargs)
  File "/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/impl/dynamic/mul.py", line 1116, in mul_compute
    res = tbe.vmul(input1, input2)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/tbe/dsl/api.py", line 210, in vmul
    return math.vmul(lhs, rhs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/tbe/common/testing/dsl_source_info.py", line 40, in wrapper
    f_return = func(*args, **kwargs)
  File "</home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/decorator.py:decorator-gen-32>", line 2, in vmul
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/tbe/dsl/compute/util.py", line 1280, in dtype_check_decorator
    return func(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/tbe/dsl/compute/math.py", line 788, in vmul
    return __binary_elewise_op(lhs, rhs, "elewise_binary_mul")
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/tbe/dsl/compute/math.py", line 1410, in __binary_elewise_op
    _check_elewise_binary_shape(tensor_l, tensor_r)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/tbe/dsl/compute/math.py", line 1501, in _check_elewise_binary_shape
    raise RuntimeError(dict_args, get_error_message(dict_args))
RuntimeError: ({'errCode': 'E90001', 'detailed_cause': 'lhs shape [(int64)3397386240] and rhs shape [-897581056] need be equal!'}, 'Compile operator failed, cause: Parameters check failed, detailed information: lhs shape [(int64)3397386240] and rhs shape [-897581056] need be equal!.')

----------------------------------------------------
- The Function Call Stack: (For framework developers)
----------------------------------------------------
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/attention.py:348/            attn = self.softmax(sim.astype(ms.float32)).astype(v.dtype)/
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/attention.py:234/            out = self.attention(q, k, v, mask)/
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/attention.py:203/        if (/
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/attention.py:442/        x = self.attn1(self.norm1(x)) + x/
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/attention.py:532/            x = block(x, context=context)/
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/attention.py:531/        for block in self.transformer_blocks:/
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/diffusionmodules/openaimodel.py:691/        for i, celllist in enumerate(self.input_blocks, 1):/
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/diffusionmodules/openaimodel.py:693/                h = cell(h, emb, context)/
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/diffusionmodules/openaimodel.py:692/            for cell in celllist:/
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/ddpm.py:448/            out = self.diffusion_model(x, t, **kwargs)/
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/modules/diffusionmodules/openaimodel.py:674/        assert (y is not None) == (/
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/ddpm.py:454/            out = self.diffusion_model(x, t, context=context, **kwargs)/
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/ddpm.py:452/        elif self.conditioning_key == "crossattn":/
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/ddpm.py:449/        elif self.conditioning_key == "concat":/
In file /home/ma-user/work/mindone/examples/stable_diffusion_v2/ldm/models/diffusion/ddpm.py:447/        if self.conditioning_key is None:/

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/plugin/device/ascend/hal/device/kernel_build_ascend.cc:132 KernelBuildParallelCompile

## Special notes for this issue | 其他信息
执行命令：python text_to_image.py --prompt "elven forest" --H 768 --W 768  -v 2.0-v

**Comment by Songyuanwei** [comment]
请使用新版本mindspore, 2.2或者2.3. mindspore2.0版本太老了
